languageCode = "en-us"
title = "Blog | Alexis Danizan"
baseurl = "https://alexisdanizan.github.io/blog/public/"
relativeURLs = true
theme = "code-editor"

[params]
    author = "Alexis Danizan"
    locale = "en-US"
