languageCode = "en-us"
title = "Blog | Alexis Danizan"
baseurl = "https://alexisdanizan.github.io/blog/public/"
theme = "code-editor"
author = "Alexis Danizan"
copyright = " Copyright (c) 2017, Alexis Danizan; all right reserved."
canonifyURLs = true
enableRobotsTXT = true
paginate = 3

[params]
    author = "Alexis Danizan"
    locale = "en-US"
